"""
Given two strings s and t which consist of only lowercase letters. String t is generated by random 
shuffling string s and then add one more letter at a random position. Find the letter that was added 
in t.

Example:
    Input: s = "abcd", t = "abcde"
    Output: e
    Explanation: 'e' is the letter that was added.
"""
from collections import Counter


class Solution:
    def findTheDifference1(self, s, t):  # 24ms
        for tt in t:
            if s.count(tt) != t.count(tt):
                return tt

    def findTheDifference2(self, s, t):  # 20ms
        return (Counter(t) - Counter(s)).popitem()[0]
        # return list((Counter(t) - Counter(s)).keys())[0]
